import re
from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, EmailStr, field_validator

from app.database.models import OrganizationType


def _validate_org_key(v: Optional[str]) -> Optional[str]:
    """Shared key validation: 2–7 uppercase letters A–Z.  Returns normalised key or raises."""
    if v is None:
        return v
    k = str(v).strip().upper()
    if not k:
        return None
    if not 2 <= len(k) <= 7:
        raise ValueError("Key must be 2–7 characters")
    if not k.isalpha():
        raise ValueError("Key must contain only letters A–Z (no digits or symbols)")
    return k


class OrganizationBase(BaseModel):
    name: str
    type: OrganizationType
    email: EmailStr
    industry: str
    country: str
    regions_operation: Optional[str] = None
    number_subsidiaries: Optional[str] = None
    company_overview: Optional[str] = None
    languages: Optional[str] = None


class OrganizationCreate(OrganizationBase):
    # key is NOT accepted on create — auto-generated by the endpoint
    pass


class OrganizationUpdate(BaseModel):
    name: Optional[str] = None
    type: Optional[OrganizationType] = None
    email: Optional[EmailStr] = None
    industry: Optional[str] = None
    country: Optional[str] = None
    regions_operation: Optional[str] = None
    number_subsidiaries: Optional[str] = None
    company_overview: Optional[str] = None
    languages: Optional[str] = None
    key: Optional[str] = None   # 2–7 uppercase letters; validated below
    csm_id: Optional[UUID] = None
    account_executive_id: Optional[UUID] = None
    sales_representative_id: Optional[UUID] = None
    account_status: Optional[str] = None
    health_score_question_id: Optional[str] = None

    @field_validator("key", mode="before")
    @classmethod
    def validate_key(cls, v):
        return _validate_org_key(v)


class OrganizationRead(OrganizationBase):
    id: UUID
    key: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    regions_operation: Optional[str] = None
    number_subsidiaries: Optional[str] = None
    company_overview: Optional[str] = None
    languages: Optional[str] = None
    csm_id: Optional[UUID] = None
    account_executive_id: Optional[UUID] = None
    sales_representative_id: Optional[UUID] = None
    account_status: Optional[str] = None
    health_score_question_id: Optional[str] = None
